# Generated by Django 5.1.2 on 2025-04-30 02:12

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to=blogs.models.renombrar_imagen),
        ),
    ]
