# Generated by Django 5.1.2 on 2025-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_imagen_descripcion_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
