# Generated by Django 5.1.2 on 2025-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seccion',
            field=models.CharField(default='blog1', max_length=100),
        ),
    ]
